config/routes.rb
Rails.application.routes.draw do

  resources :recommendations
  delete 'delete_rec' => 'recommendations#destroy'
  post 'derp' => 'recommendations#create'
  post 'upvote' => 'home#upvote'
  devise_for :users
  root 'home#index'
  get 'recs' => 'home#recs'
  get 'seen' => 'home#seen'

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :recommendation
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@recommendations = Recommendation.all
    @not_seen_movies = Recommendation.where(watched: false).all
  end 

  def recs

  		@all_movies	= Tmdb::Movie.now_playing

  end

  def upvote
  	@recommendation = Recommendation.find(params[:id])
  	@recommendation.votes += 1
  	 @recommendation.save
  	 redirect_to '/'

  end

  def seen

  	@seen_movies = Recommendation.where(watched: true).all

  end


end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  # before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show

    @recommendation = Recommendation.where(user_id: current_user.id)
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
    
  end

  # GET /recommendations/1/edit
  def edit
    @recommendation = Recommendation.find(params[:id])
    
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to '/', notice: 'Recommendation was successfully created.' }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    @recommendation = Recommendation.find(params[:id])

    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation = Recommendation.find(params[:id])

    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Recommendation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:title, :genre, :watched, :votes, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
<div class="row" id="Middle-text"><h1 style="color:gray">Here are your friend's recommendations!</h1></div>

<div class="container-fluid-user-home">
<div class="row"> 
  <aside class="span8">
  <div class="row" id="button-middle">
  <section>
      
        <form action= 'recommendations/new' method="GET">
        <input name="" type="submit" class="btn btn-success" name="activate" value="Add Recommendation!"/>
        </form>
   

        </h1>
        </section>
        </aside>
        </div>

  <table>
  <thead>
    <tr>
      <th style="color:gray"><h4>Title</h4></th>
      <th></th>
      <th style="color:gray"><h4>Genre</h4></th>
      <th></th>
      <th style="color:gray"><h4>Watched</h4></th>
      <th></th>
      <th style="color:gray"><h4>Votes</h4></th>
      <th></th>
      <th style="color:gray"><h4>User</h4></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @not_seen_movies.each do |recommendation| %>

      <tr>
        <td><h4><%= recommendation.title %></h4></td>
        <td></td>
        <td><h4><%= recommendation.genre %></h4></td>
        <td></td>
        <td><h4><%= recommendation.watched %></h4></td>
        <td></td>
        <td><h4><%= recommendation.votes %></h4></td>
        <td></td>
        <td><h4><%= recommendation.user.email %></h4></td>
        <td></td>
        <% if recommendation.user.id == current_user.id%>
        



        <td><%= link_to 'Kill it', recommendation, method: :delete, data: { confirm: 'Seriously?' } %></td>
       


        <%else%> 
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
    

        <% else %>
<p style="color:green;margin-left:20px;">Go ahead and sign up or sign in</p>


<p> <%= link_to 'Sign In', new_user_session_path %> </p>
<p> <%= link_to 'Sign Up', new_user_registration_path %> </p>

<% end %>

app/views/home/recs.html.erb
<div class="container-fluid-user-home">
<div class="row">

<table>
  <thead>
    <tr>
      <th><h1>Title</h1></th>
      <th></th>
      <th></th>
      <th></th>
      <th><h1>Popularity</h1></th>
      <th></th>
      <th></th>
      <th></th>
      <th><h1>Poster</h1></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @all_movies.each do |recommendation| %>
    <% if recommendation.poster_path != nil%>
      <tr>
        <td><h2><%= recommendation.title %></h2></td>
        <td></td>
        <td><h4></h4></td>
        <td></td>
        <td><h2><%= recommendation.vote_average %></h2></td>
        <td></td>
        <td><h4><%= recommendation.realease_date %></h4></td>
        <td></td>

        <td><h4><img src="http://image.tmdb.org/t/p/w154/<%=recommendation["poster_path"]%>"></h4></td>
        <td></td>
        <%else%>
        <%end%>

        <%end%>

      </tr>

    
  </tbody>
</table>
</div>
</div>

app/views/home/seen.html.erb
<div class="container-fluid">
<div class="row">

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
      <th>Genre</th>
      <th></th>
      <th>Watched?</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seen_movies.each do |recommendation| %>
    
      <tr>
        <td><h2><%= recommendation.title %></h2></td>
        <td></td>
        <td><h4></h4></td>
        <td></td>
        <td><h4><%= recommendation.genre %></h4></td>
        <td></td>
        <td><h4><%= recommendation.watched %></h4></td>
        <td></td>

        
        
       
 
        
        <%end%>
      </tr>
    
  </tbody>
</table>
</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-fixed-bottom navbar-inverse">
  <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right">

        <li><%= link_to "Sitemap", "#" %></li>
        <li><%= link_to "Pics", "#" %></li>
		</ul>
      <a class="navbar-brand" href="#"><%= @first_visit %></a>
   
 -->
      
     

      </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">


         <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-sound-6-1"></span></a>
     
          <div class="nav navbar-nav pull-right">
           
          <% if user_signed_in? %> 
         <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle" >Settings<span class="white"></span></a>
                  <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Home", '/' %></li>
                  <li><%= link_to "Edit", edit_user_registration_path %></li>
                  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                  
                </ul>
             </li> 
             <li><%= link_to("Recommendations!", '/recs')%>
             <li><%= link_to("Saw It!", '/seen')%>
             <% else %>

             <li><%= link_to("Sign In", new_user_session_path)%></li>
             <% end %>
         

               
           
         
            </div> 

            </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<body>

<%= render 'layouts/header' %>
<div class="container">
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

<%= yield %>

</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/recommendations/_form.html.erb
 


<%= form_for(@recommendation) do |f| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% @recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <% f.label :watched %><br>
    <%= f.hidden_field :watched ,value: 'false' %>
  </div>
  <div class="field">
    <%  f.label :votes %><br>
    <%= f.hidden_field :votes, value: '1' %>
  </div>
  <div class="field">
    <% f.label :user_id %><br>
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<h1>Editing recommendation</h1>

<%= render 'form' %>

app/views/recommendations/index.html.erb
<h1>Listing recommendations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Watched</th>
      <th>Votes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommendations.each do |recommendation| %>
    
      <tr>
        <td><%= recommendation.title %></td>
        <td><%= recommendation.genre %></td>
        <td><%= recommendation.watched %></td>
        <td><%= recommendation.votes %></td>
        <td><%= recommendation.user_id %></td>
        <td><%= link_to 'Show', recommendation %></td>
        <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
        <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/recommendations/new.html.erb
<h1>New recommendation</h1>

<%= render 'form' %>

app/views/recommendations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recommendation.title %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @recommendation.genre %>
</p>

<p>
  <strong>Watched:</strong>
  <%= @recommendation.watched %>
</p>

<p>
  <strong>Votes:</strong>
  <%= @recommendation.votes %>
</p>

<p>
  <strong>User:</strong>
  <%= @recommendation.user_id %>
</p>